### ISSUE TITLE
[UIWindow setScreen:] with UIScene 

### ISSUE THREAD

**Issue by ataourirt** [zendesk/sunshine-conversations-ios#214] opened 2021-03-11 16:59 UTC
I have embedded the Smooch `UIViewController` in an another Custom `UIViewController. When I click on "+" (to opening conversations actions like Take Photo), many errors appear in Xcode console: 

**[Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.**

We have also some breaking constraints.

After that, nothing appear, the access of actions is **impossible**.

- SDK version : 10.1.0
- OS version: 14.4

Thx for your support

**Comment by IAmConorNolan** [comment] 2021-03-11 17:11
Hey @ataourirt,

I've had a look and can't reproduce your issue. We did ship a fix for this issue in 10.1.0 - would you mind ensuring you are up to date?

If that fails to solve your issue, could you please provide your initialization code along with the code you use to show the conversation? Thanks!

**Comment by ataourirt** [comment] 2021-03-11 17:32
Thx @IAmConorNolan for your quickly response!

Indeed I had version 10.0.0 and not 10.1.0. The list of actions now appears!

But I have always breakings constraints : 

```
2021-03-11 18:27:39.847115+0100 [63864:3109771] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000088d360 UIView:0x7f9cde61df40.width == - 16   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000088d360 UIView:0x7f9cde61df40.width == - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

This is how the UIViewController is integrated:
``` 
   let openVCCompletion = { [weak self] (error: Error?, vc: UIViewController?) -> Void in
      guard let self = self else { return }
      self.conversationVC = vc
      guard let sdkConversationVC = self.conversationVC else { return }
      self.addChild(sdkConversationVC)
      self.view.addSubview(sdkConversationVC.view)
      
      sdkConversationVC.view.translatesAutoresizingMaskIntoConstraints = false
      var constraints = [NSLayoutConstraint]()
      
      constraints.append(sdkConversationVC.view.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor))
      constraints.append(sdkConversationVC.view.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor))
      constraints.append(sdkConversationVC.view.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor))
      constraints.append(sdkConversationVC.view.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor))

      NSLayoutConstraint.activate(constraints)
    
      sdkConversationVC.didMove(toParent: self)
    }
```

Have you any ideas about the provenance of these errors ?

Thx!

**Comment by IAmConorNolan** [comment] 2021-03-12 10:07
Hey @ataourirt - glad this sorted the issue out for you, and the actions are now appearing :) 

The issue relating to constraints has been added to our backlog and passed along to the development team. Thanks for your feedback!

**Closed by IAmConorNolan** 2021-03-12 10:07 UTC
